-- SQL portable PostgreSQL / H2 (les tests d'integration tournent sur H2 en mode PostgreSQL).

CREATE TABLE chat_users (
    id           UUID PRIMARY KEY,
    nickname     VARCHAR(24) NOT NULL,
    nickname_key VARCHAR(24) NOT NULL UNIQUE,
    color        VARCHAR(16) NOT NULL,
    token_hash   VARCHAR(64) UNIQUE,
    bot          BOOLEAN     NOT NULL DEFAULT FALSE,
    created_at   TIMESTAMP WITH TIME ZONE NOT NULL,
    last_seen_at TIMESTAMP WITH TIME ZONE
);

CREATE TABLE rooms (
    id         UUID PRIMARY KEY,
    name       VARCHAR(32) NOT NULL UNIQUE,
    topic      VARCHAR(160),
    created_by UUID REFERENCES chat_users (id) ON DELETE SET NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE memberships (
    room_id              UUID NOT NULL REFERENCES rooms (id) ON DELETE CASCADE,
    user_id              UUID NOT NULL REFERENCES chat_users (id) ON DELETE CASCADE,
    last_read_message_id BIGINT,
    joined_at            TIMESTAMP WITH TIME ZONE NOT NULL,
    PRIMARY KEY (room_id, user_id)
);

CREATE INDEX idx_memberships_user ON memberships (user_id);

CREATE TABLE messages (
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    room_id   UUID          NOT NULL REFERENCES rooms (id) ON DELETE CASCADE,
    author_id UUID          NOT NULL REFERENCES chat_users (id),
    content   VARCHAR(2000) NOT NULL,
    sent_at   TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE INDEX idx_messages_room ON messages (room_id, id DESC);
